### ISSUE TITLE
Production/performance impact of connecting a socket per message?

### ISSUE THREAD

**Issue by wyantb** [shelfio/winston-datadog-logs-transport#58]
Hey @shelfio, huge thanks for this library! This made it really easy to connect up to datadog in some of our low-usage servers without hassle.

I have a question related to how you send the messages in https://github.com/shelfio/winston-datadog-logs-transport/blob/master/index.js#L36 , however. Basically: in your experience, does it cause any significant performance impact to connect the socket each time? I'm worried that if I set this up on one of my higher traffic servers that connecting a socket each time might hit some limits on the box we're running on and/or cause excess memory/CPU usage. Any thoughts or empirical evidence on this question would be great, if you have it.

https://medium.com/expedia-group-tech/under-the-hood-of-http-requests-in-node-69e27e2cd528 gives me some expectation that creating a new socket per message isn't ideal; storing an instance of `http.Agent` with maxSockets of 5 or similar and doing a https://nodejs.org/api/http.html#http_agent_createconnection_options_callback call per message (which returns a stream.Duplex, may be compatible with how you're using the TLSSocket) may be the way to go. This theory is certainly untested however...

Thanks again!

**Comment by vladholubiev** [comment]
Hey @wyantb,

thanks for the kind words. Unfortunately, we are no longer using this library here at @shelfio. So I'm afraid I can't share real usage experience.

**Comment by wyantb** [comment]
Understood. I'll take a look myself, then. Thanks!
